// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlToMySql.Data;

#nullable disable

namespace SqlToMySql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250227103844_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SqlToMySql.Data.models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SqlToMySql.Data.models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("IBAN")
                        .HasColumnType("longtext");

                    b.Property<string>("Interests")
                        .HasColumnType("longtext");

                    b.Property<string>("Introduction")
                        .HasColumnType("longtext");

                    b.Property<string>("KnownAs")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("LookingFor")
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("PaidTill")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("hospital_id")
                        .HasColumnType("int");

                    b.Property<bool>("ltk")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("worked_in")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SqlToMySql.Data.models.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId1")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId1");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_Aortic_Surgery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Dissection")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Dissection_onset")
                        .HasColumnType("longtext");

                    b.Property<bool>("aneurysm")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("aneurysm_type")
                        .HasColumnType("longtext");

                    b.Property<bool>("coarctation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("dissection_type")
                        .HasColumnType("longtext");

                    b.Property<string>("indication")
                        .HasColumnType("longtext");

                    b.Property<string>("operative_technique")
                        .HasColumnType("longtext");

                    b.Property<bool>("other_congenital")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("pathology")
                        .HasColumnType("longtext");

                    b.Property<int>("procedure_id")
                        .HasColumnType("int");

                    b.Property<string>("range")
                        .HasColumnType("longtext");

                    b.Property<string>("stent_graft_technique")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Aosurgeries");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_CABG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ANGLE01")
                        .HasColumnType("longtext");

                    b.Property<string>("ANGLE02")
                        .HasColumnType("longtext");

                    b.Property<string>("ANGLE03")
                        .HasColumnType("longtext");

                    b.Property<string>("ANGLE04")
                        .HasColumnType("longtext");

                    b.Property<string>("ANGLE05")
                        .HasColumnType("longtext");

                    b.Property<string>("ANGLE06")
                        .HasColumnType("longtext");

                    b.Property<string>("B1_CONDUIT")
                        .HasColumnType("longtext");

                    b.Property<string>("B1_DONOR")
                        .HasColumnType("longtext");

                    b.Property<string>("B1_LOCPROC")
                        .HasColumnType("longtext");

                    b.Property<string>("B1_SITE")
                        .HasColumnType("longtext");

                    b.Property<string>("B1_SITEPA")
                        .HasColumnType("longtext");

                    b.Property<string>("B1_TYPE_DA")
                        .HasColumnType("longtext");

                    b.Property<string>("B2_CONDUIT")
                        .HasColumnType("longtext");

                    b.Property<string>("B2_DONOR")
                        .HasColumnType("longtext");

                    b.Property<string>("B2_LOCPROC")
                        .HasColumnType("longtext");

                    b.Property<string>("B2_SITE")
                        .HasColumnType("longtext");

                    b.Property<string>("B2_SITEPA")
                        .HasColumnType("longtext");

                    b.Property<string>("B2_TYPE_DA")
                        .HasColumnType("longtext");

                    b.Property<string>("B3_CONDUIT")
                        .HasColumnType("longtext");

                    b.Property<string>("B3_DONOR")
                        .HasColumnType("longtext");

                    b.Property<string>("B3_LOCPROC")
                        .HasColumnType("longtext");

                    b.Property<string>("B3_SITE")
                        .HasColumnType("longtext");

                    b.Property<string>("B3_SITEPA")
                        .HasColumnType("longtext");

                    b.Property<string>("B3_TYPE_DA")
                        .HasColumnType("longtext");

                    b.Property<string>("B4_CONDUIT")
                        .HasColumnType("longtext");

                    b.Property<string>("B4_DONOR")
                        .HasColumnType("longtext");

                    b.Property<string>("B4_LOCPROC")
                        .HasColumnType("longtext");

                    b.Property<string>("B4_SITE")
                        .HasColumnType("longtext");

                    b.Property<string>("B4_SITEPA")
                        .HasColumnType("longtext");

                    b.Property<string>("B4_TYPE_DA")
                        .HasColumnType("longtext");

                    b.Property<string>("B5_CONDUIT")
                        .HasColumnType("longtext");

                    b.Property<string>("B5_DONOR")
                        .HasColumnType("longtext");

                    b.Property<string>("B5_LOCPROC")
                        .HasColumnType("longtext");

                    b.Property<string>("B5_SITE")
                        .HasColumnType("longtext");

                    b.Property<string>("B5_SITEPA")
                        .HasColumnType("longtext");

                    b.Property<string>("B5_TYPE_DA")
                        .HasColumnType("longtext");

                    b.Property<string>("B6_CONDUIT")
                        .HasColumnType("longtext");

                    b.Property<string>("B6_DONOR")
                        .HasColumnType("longtext");

                    b.Property<string>("B6_LOCPROC")
                        .HasColumnType("longtext");

                    b.Property<string>("B6_SITE")
                        .HasColumnType("longtext");

                    b.Property<string>("B6_SITEPA")
                        .HasColumnType("longtext");

                    b.Property<string>("B6_TYPE_DA")
                        .HasColumnType("longtext");

                    b.Property<string>("CAB")
                        .HasColumnType("longtext");

                    b.Property<string>("DIAM01")
                        .HasColumnType("longtext");

                    b.Property<string>("DIAM02")
                        .HasColumnType("longtext");

                    b.Property<string>("DIAM03")
                        .HasColumnType("longtext");

                    b.Property<string>("DIAM04")
                        .HasColumnType("longtext");

                    b.Property<string>("DIAM05")
                        .HasColumnType("longtext");

                    b.Property<string>("DIAM06")
                        .HasColumnType("longtext");

                    b.Property<int?>("PATIENT_ID")
                        .HasColumnType("int");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("int");

                    b.Property<string>("Q01")
                        .HasColumnType("longtext");

                    b.Property<string>("Q02")
                        .HasColumnType("longtext");

                    b.Property<string>("Q03")
                        .HasColumnType("longtext");

                    b.Property<string>("Q04")
                        .HasColumnType("longtext");

                    b.Property<string>("Q05")
                        .HasColumnType("longtext");

                    b.Property<string>("Q06")
                        .HasColumnType("longtext");

                    b.Property<string>("UNPLANNED_CAB")
                        .HasColumnType("longtext");

                    b.Property<string>("art01")
                        .HasColumnType("longtext");

                    b.Property<string>("art02")
                        .HasColumnType("longtext");

                    b.Property<string>("art03")
                        .HasColumnType("longtext");

                    b.Property<string>("art04")
                        .HasColumnType("longtext");

                    b.Property<string>("art05")
                        .HasColumnType("longtext");

                    b.Property<string>("art06")
                        .HasColumnType("longtext");

                    b.Property<string>("course")
                        .HasColumnType("longtext");

                    b.Property<string>("leg_harvest_location")
                        .HasColumnType("longtext");

                    b.Property<string>("leg_harvest_technique")
                        .HasColumnType("longtext");

                    b.Property<string>("radial_harvest_location")
                        .HasColumnType("longtext");

                    b.Property<string>("radial_harvest_technique")
                        .HasColumnType("longtext");

                    b.Property<int?>("tachtig_switch")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cabgs");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_CPB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Antiarrhythmics")
                        .HasColumnType("int");

                    b.Property<string>("BVAD")
                        .HasColumnType("longtext");

                    b.Property<string>("CARDIOPLEGIA")
                        .HasColumnType("longtext");

                    b.Property<int?>("CARDIOPLEGIA_TEMP_COLD")
                        .HasColumnType("int");

                    b.Property<int?>("CARDIOPLEGIA_TEMP_WARM")
                        .HasColumnType("int");

                    b.Property<string>("CARDIOPLEGIA_TYPE")
                        .HasColumnType("longtext");

                    b.Property<int?>("CARDIOVERSION")
                        .HasColumnType("int");

                    b.Property<int>("CROSS_CLAMP_TIME")
                        .HasColumnType("int");

                    b.Property<string>("IABP")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("IABP_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("IABP_IND")
                        .HasColumnType("longtext");

                    b.Property<string>("IABP_OPTIONS")
                        .HasColumnType("longtext");

                    b.Property<int?>("INFUSION_DOSE_CONT")
                        .HasColumnType("int");

                    b.Property<int?>("INFUSION_DOSE_INT")
                        .HasColumnType("int");

                    b.Property<string>("INFUSION_MODE_ANTE")
                        .HasColumnType("longtext");

                    b.Property<int?>("INFUSION_MODE_RETRO")
                        .HasColumnType("int");

                    b.Property<int?>("INOTROPES")
                        .HasColumnType("int");

                    b.Property<int?>("LOWEST_CORE_TEMP")
                        .HasColumnType("int");

                    b.Property<int?>("LVAD")
                        .HasColumnType("int");

                    b.Property<int?>("PACING_ATRIAL")
                        .HasColumnType("int");

                    b.Property<int?>("PACING_HARV")
                        .HasColumnType("int");

                    b.Property<int?>("PACING_VENTRICULAR")
                        .HasColumnType("int");

                    b.Property<int>("PERFUSION_TIME")
                        .HasColumnType("int");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("int");

                    b.Property<int?>("RVAD")
                        .HasColumnType("int");

                    b.Property<int?>("SKIN_INCISION_START_TIME")
                        .HasColumnType("int");

                    b.Property<int?>("SKIN_INCISION_STOP_TIME")
                        .HasColumnType("int");

                    b.Property<string>("TAH")
                        .HasColumnType("longtext");

                    b.Property<string>("VAD")
                        .HasColumnType("longtext");

                    b.Property<string>("a1")
                        .HasColumnType("longtext");

                    b.Property<string>("a2")
                        .HasColumnType("longtext");

                    b.Property<string>("a3")
                        .HasColumnType("longtext");

                    b.Property<string>("a4")
                        .HasColumnType("longtext");

                    b.Property<string>("acp_circ")
                        .HasColumnType("longtext");

                    b.Property<string>("aoOCCL")
                        .HasColumnType("longtext");

                    b.Property<string>("cardiac_support")
                        .HasColumnType("longtext");

                    b.Property<string>("cardiopl_temp")
                        .HasColumnType("longtext");

                    b.Property<string>("cardiopl_timing")
                        .HasColumnType("longtext");

                    b.Property<int?>("clamp_start_hr")
                        .HasColumnType("int");

                    b.Property<int?>("clamp_start_min")
                        .HasColumnType("int");

                    b.Property<int?>("clamp_stop_hr")
                        .HasColumnType("int");

                    b.Property<int?>("clamp_stop_min")
                        .HasColumnType("int");

                    b.Property<string>("cns_protect")
                        .HasColumnType("longtext");

                    b.Property<int?>("cns_time_1")
                        .HasColumnType("int");

                    b.Property<int?>("cns_time_2")
                        .HasColumnType("int");

                    b.Property<int?>("cns_time_3")
                        .HasColumnType("int");

                    b.Property<int?>("cpb_start_hr")
                        .HasColumnType("int");

                    b.Property<int?>("cpb_start_min")
                        .HasColumnType("int");

                    b.Property<int?>("cpb_stop_hr")
                        .HasColumnType("int");

                    b.Property<int?>("cpb_stop_min")
                        .HasColumnType("int");

                    b.Property<string>("cpb_used")
                        .HasColumnType("longtext");

                    b.Property<string>("deep_hypo")
                        .HasColumnType("longtext");

                    b.Property<string>("deep_hypo_rcp")
                        .HasColumnType("longtext");

                    b.Property<int?>("long_isch")
                        .HasColumnType("int");

                    b.Property<string>("myoplasty")
                        .HasColumnType("longtext");

                    b.Property<string>("nonCMProtect")
                        .HasColumnType("longtext");

                    b.Property<short?>("nonCMProtect_type")
                        .HasColumnType("smallint");

                    b.Property<string>("opcab_attempt")
                        .HasColumnType("longtext");

                    b.Property<string>("other_cardiac_support")
                        .HasColumnType("longtext");

                    b.Property<string>("other_cns_protect")
                        .HasColumnType("longtext");

                    b.Property<string>("v1")
                        .HasColumnType("longtext");

                    b.Property<string>("v2")
                        .HasColumnType("longtext");

                    b.Property<string>("v3")
                        .HasColumnType("longtext");

                    b.Property<string>("v4")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cpbs");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CCS")
                        .HasColumnType("longtext");

                    b.Property<int>("EuroScoreNo")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("IsPreviousIntervention")
                        .HasColumnType("longtext");

                    b.Property<string>("LVEF")
                        .HasColumnType("longtext");

                    b.Property<string>("MRN")
                        .HasColumnType("longtext");

                    b.Property<string>("NOPM")
                        .HasColumnType("longtext");

                    b.Property<string>("NYHA")
                        .HasColumnType("longtext");

                    b.Property<string>("active_endocarditis")
                        .HasColumnType("longtext");

                    b.Property<string>("copd")
                        .HasColumnType("longtext");

                    b.Property<int>("creat_number")
                        .HasColumnType("int");

                    b.Property<bool>("crit_arrythmia")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("crit_iabp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("crit_inotropes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("crit_pacemaker")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("crit_renal_failure")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("crit_resuscitation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("crit_shock")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("crit_ventilated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("critical_preoperative_state")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("dead")
                        .HasColumnType("int");

                    b.Property<string>("diabetes_on_insulin")
                        .HasColumnType("longtext");

                    b.Property<bool>("dialysis")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("extra_cardiac_arteriopathy")
                        .HasColumnType("longtext");

                    b.Property<string>("gender")
                        .HasColumnType("longtext");

                    b.Property<string>("height")
                        .HasColumnType("longtext");

                    b.Property<string>("log_score")
                        .HasColumnType("longtext");

                    b.Property<string>("poor_mobility")
                        .HasColumnType("longtext");

                    b.Property<string>("previous_cardiac_surgery")
                        .HasColumnType("longtext");

                    b.Property<string>("reason_emergent")
                        .HasColumnType("longtext");

                    b.Property<string>("reason_urgent")
                        .HasColumnType("longtext");

                    b.Property<string>("recent_mi")
                        .HasColumnType("longtext");

                    b.Property<int>("soort_procedure")
                        .HasColumnType("int");

                    b.Property<string>("surgery_on_thoracic_aorta")
                        .HasColumnType("longtext");

                    b.Property<string>("systolic_pa_pressure")
                        .HasColumnType("longtext");

                    b.Property<string>("timing")
                        .HasColumnType("longtext");

                    b.Property<string>("weight")
                        .HasColumnType("longtext");

                    b.Property<string>("weight_of_intervention")
                        .HasColumnType("longtext");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_PostOp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autologous_Blood")
                        .HasColumnType("longtext");

                    b.Property<string>("Blood_Products")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DISCHARGE_DATE")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EXTUBATION_1_DATE")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EXTUBATION_DATE")
                        .HasColumnType("datetime");

                    b.Property<int>("FFP")
                        .HasColumnType("int");

                    b.Property<DateTime>("ICU_ARRIVAL_1_DATE")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ICU_ARRIVAL_DATE")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ICU_DISCHARGE_1_DATE")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ICU_DISCHARGE_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("ICU_Stay_1")
                        .HasColumnType("longtext");

                    b.Property<string>("ICU_Stay_2")
                        .HasColumnType("longtext");

                    b.Property<string>("ICU_Stay_3")
                        .HasColumnType("longtext");

                    b.Property<int>("PATIENT_ID")
                        .HasColumnType("int");

                    b.Property<int>("PC")
                        .HasColumnType("int");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("int");

                    b.Property<int>("Platelets")
                        .HasColumnType("int");

                    b.Property<DateTime>("REINTUBATION_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("Vent_Stay_1")
                        .HasColumnType("longtext");

                    b.Property<string>("Vent_Stay_2")
                        .HasColumnType("longtext");

                    b.Property<string>("Vent_Stay_3")
                        .HasColumnType("longtext");

                    b.Property<string>("When_Used")
                        .HasColumnType("longtext");

                    b.Property<string>("activities_discharge")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_1")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_2")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_3")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_4")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_5")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_6")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_7")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_8")
                        .HasColumnType("longtext");

                    b.Property<string>("complicatie_9")
                        .HasColumnType("longtext");

                    b.Property<short>("dead_cause")
                        .HasColumnType("smallint");

                    b.Property<short>("dead_location")
                        .HasColumnType("smallint");

                    b.Property<short>("discharge_diagnosis")
                        .HasColumnType("smallint");

                    b.Property<string>("full_description")
                        .HasColumnType("longtext");

                    b.Property<string>("highest_creatinine")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("mortality_date")
                        .HasColumnType("datetime");

                    b.Property<short>("overleden_na_deze_operatie")
                        .HasColumnType("smallint");

                    b.Property<string>("readmitted")
                        .HasColumnType("longtext");

                    b.Property<string>("reintubated")
                        .HasColumnType("longtext");

                    b.Property<string>("sent_to")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PostOps");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_Procedure", b =>
                {
                    b.Property<int>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Class_PatientPatientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment1")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment2")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment3")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfSurgery")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedAnaesthesist")
                        .HasColumnType("int");

                    b.Property<int>("SelectedAssistant")
                        .HasColumnType("int");

                    b.Property<int>("SelectedEmergencyTiming")
                        .HasColumnType("int");

                    b.Property<int>("SelectedInotropes")
                        .HasColumnType("int");

                    b.Property<int>("SelectedNurse1")
                        .HasColumnType("int");

                    b.Property<int>("SelectedNurse2")
                        .HasColumnType("int");

                    b.Property<int>("SelectedPacemaker")
                        .HasColumnType("int");

                    b.Property<int>("SelectedPerfusionist")
                        .HasColumnType("int");

                    b.Property<int>("SelectedPericard")
                        .HasColumnType("int");

                    b.Property<int>("SelectedPleura")
                        .HasColumnType("int");

                    b.Property<int>("SelectedResponsibleSurgeon")
                        .HasColumnType("int");

                    b.Property<int>("SelectedStartHr")
                        .HasColumnType("int");

                    b.Property<int>("SelectedStartMin")
                        .HasColumnType("int");

                    b.Property<int>("SelectedStopHr")
                        .HasColumnType("int");

                    b.Property<int>("SelectedStopMin")
                        .HasColumnType("int");

                    b.Property<int>("SelectedSurgeon")
                        .HasColumnType("int");

                    b.Property<int>("SelectedTiming")
                        .HasColumnType("int");

                    b.Property<int>("SelectedUrgentTiming")
                        .HasColumnType("int");

                    b.Property<string>("Sequence")
                        .HasColumnType("longtext");

                    b.Property<bool>("SurgeryBeforeNextWorkingDay")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TotalTime")
                        .HasColumnType("int");

                    b.Property<string>("emailHash")
                        .HasColumnType("longtext");

                    b.Property<int>("fdType")
                        .HasColumnType("int");

                    b.Property<int>("hospital")
                        .HasColumnType("int");

                    b.Property<int>("refPhys")
                        .HasColumnType("int");

                    b.HasKey("ProcedureId");

                    b.HasIndex("Class_PatientPatientId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_Valve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Combined")
                        .HasColumnType("longtext");

                    b.Property<string>("EXPLANT")
                        .HasColumnType("longtext");

                    b.Property<string>("IMPLANT")
                        .HasColumnType("longtext");

                    b.Property<string>("Implant_Position")
                        .HasColumnType("longtext");

                    b.Property<string>("MODEL")
                        .HasColumnType("longtext");

                    b.Property<string>("MODEL_EXP")
                        .HasColumnType("longtext");

                    b.Property<string>("Memo")
                        .HasColumnType("longtext");

                    b.Property<string>("ProcedureAetiology")
                        .HasColumnType("longtext");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("int");

                    b.Property<string>("ProcedureType")
                        .HasColumnType("longtext");

                    b.Property<string>("REPAIR_TYPE")
                        .HasColumnType("longtext");

                    b.Property<string>("RING_USED")
                        .HasColumnType("longtext");

                    b.Property<string>("SERIAL_EXP")
                        .HasColumnType("longtext");

                    b.Property<string>("SERIAL_IMP")
                        .HasColumnType("longtext");

                    b.Property<string>("SIZE")
                        .HasColumnType("longtext");

                    b.Property<string>("SIZE_EXP")
                        .HasColumnType("longtext");

                    b.Property<string>("TYPE")
                        .HasColumnType("longtext");

                    b.Property<int?>("TYPE_EXP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureId");

                    b.ToTable("Valves");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_minInv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ACUTE_FLOW")
                        .HasColumnType("int");

                    b.Property<int>("ACUTE_FLOW_DETAILS")
                        .HasColumnType("int");

                    b.Property<int>("AL_TIME")
                        .HasColumnType("int");

                    b.Property<int>("CONVERSION_DETAILS")
                        .HasColumnType("int");

                    b.Property<int>("CONVERSION_TO_STANDARD")
                        .HasColumnType("int");

                    b.Property<int>("CX_TIME")
                        .HasColumnType("int");

                    b.Property<int>("IABP")
                        .HasColumnType("int");

                    b.Property<int>("IABP_WHEN")
                        .HasColumnType("int");

                    b.Property<int>("IABP_WHY")
                        .HasColumnType("int");

                    b.Property<int>("LAD_TIME")
                        .HasColumnType("int");

                    b.Property<int>("LIMA_HARVEST")
                        .HasColumnType("int");

                    b.Property<int>("NUMBER_OF_INCISIONS")
                        .HasColumnType("int");

                    b.Property<int>("PRIMARY_INCISION")
                        .HasColumnType("int");

                    b.Property<int>("PRIMARY_INCISION_DETAILS")
                        .HasColumnType("int");

                    b.Property<int>("PROCEDURE_ID")
                        .HasColumnType("int");

                    b.Property<int>("RCA_TIME")
                        .HasColumnType("int");

                    b.Property<int>("ROBOT")
                        .HasColumnType("int");

                    b.Property<int>("ROBOT_AORTIC")
                        .HasColumnType("int");

                    b.Property<int>("ROBOT_CABG")
                        .HasColumnType("int");

                    b.Property<int>("ROBOT_MITRAL")
                        .HasColumnType("int");

                    b.Property<int>("ROBOT_PULMONARY")
                        .HasColumnType("int");

                    b.Property<int>("ROBOT_TRICUSPID")
                        .HasColumnType("int");

                    b.Property<int>("SHUNT")
                        .HasColumnType("int");

                    b.Property<int>("STRATEGY")
                        .HasColumnType("int");

                    b.Property<int>("SUTURE")
                        .HasColumnType("int");

                    b.Property<int>("VESSEL")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MinInvs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SqlToMySql.Data.models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SqlToMySql.Data.models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SqlToMySql.Data.models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SqlToMySql.Data.models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlToMySql.Data.models.AppUserRole", b =>
                {
                    b.HasOne("SqlToMySql.Data.models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlToMySql.Data.models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId1");

                    b.HasOne("SqlToMySql.Data.models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlToMySql.Data.models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_Procedure", b =>
                {
                    b.HasOne("SqlToMySql.Data.models.Class_Patient", "Class_Patient")
                        .WithMany("procedures")
                        .HasForeignKey("Class_PatientPatientId");

                    b.Navigation("Class_Patient");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_Valve", b =>
                {
                    b.HasOne("SqlToMySql.Data.models.Class_Procedure", "procedure")
                        .WithMany("ValvesUsed")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("procedure");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_Patient", b =>
                {
                    b.Navigation("procedures");
                });

            modelBuilder.Entity("SqlToMySql.Data.models.Class_Procedure", b =>
                {
                    b.Navigation("ValvesUsed");
                });
#pragma warning restore 612, 618
        }
    }
}
